# Generated by Django 5.1.5 on 2026-05-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='state_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
