# Generated by Django 4.2.28 on 2026-06-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interviewsession_state_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
