# Generated by Django 4.2.28 on 2026-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_interviewsession_candidate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
